CREATE TABLE championship (
                              id       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                              name     VARCHAR2(100 CHAR) NOT NULL,
                              category VARCHAR2(20 CHAR)  NOT NULL,
                              year     NUMBER(10)         NOT NULL,

                              CONSTRAINT pk_championship PRIMARY KEY (id),
                              CONSTRAINT ck_championship_category
                                  CHECK (category IN ('SUB_13', 'SUB_15', 'SUB_17', 'SUB_20'))
);

CREATE TABLE team (
                      id    NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                      name  VARCHAR2(100 CHAR) NOT NULL,
                      city  VARCHAR2(100 CHAR) NOT NULL,
                      state VARCHAR2(2 CHAR)   NOT NULL,

                      CONSTRAINT pk_team PRIMARY KEY (id),
                      CONSTRAINT uk_team_name UNIQUE (name)
);

CREATE TABLE referee (
                         id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         name       VARCHAR2(100 CHAR) NOT NULL,
                         birth_date DATE               NOT NULL,
                         status     VARCHAR2(20 CHAR)  NOT NULL,

                         CONSTRAINT pk_referee PRIMARY KEY (id),
                         CONSTRAINT uk_referee_name UNIQUE (name),
                         CONSTRAINT ck_referee_status
                             CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

CREATE TABLE knowball_users (
                                id       NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                name     VARCHAR2(100 CHAR) NOT NULL,
                                email    VARCHAR2(150 CHAR) NOT NULL,
                                password VARCHAR2(200 CHAR) NOT NULL,
                                role     VARCHAR2(20 CHAR)  NOT NULL,

                                CONSTRAINT pk_knowball_users PRIMARY KEY (id),
                                CONSTRAINT uk_knowball_users_email UNIQUE (email),
                                CONSTRAINT ck_knowball_users_role
                                    CHECK (role IN ('ROLE_USER', 'ROLE_ADMIN'))
);

CREATE TABLE game (
                      id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                      championship_id NUMBER(19) NOT NULL,
                      match_date      TIMESTAMP  NOT NULL,
                      place           VARCHAR2(100 CHAR) NOT NULL,
                      home_score      NUMBER(10) NOT NULL,
                      away_score      NUMBER(10) NOT NULL,

                      CONSTRAINT pk_game PRIMARY KEY (id),
                      CONSTRAINT fk_game_championship
                          FOREIGN KEY (championship_id)
                              REFERENCES championship (id)
);

CREATE TABLE participation (
                               game_id NUMBER(19) NOT NULL,
                               team_id NUMBER(19) NOT NULL,
                               type    VARCHAR2(10 CHAR) NOT NULL,

                               CONSTRAINT pk_participation PRIMARY KEY (game_id, team_id),
                               CONSTRAINT fk_participation_game
                                   FOREIGN KEY (game_id)
                                       REFERENCES game (id),
                               CONSTRAINT fk_participation_team
                                   FOREIGN KEY (team_id)
                                       REFERENCES team (id),
                               CONSTRAINT ck_participation_type
                                   CHECK (type IN ('HOME', 'AWAY'))
);

CREATE TABLE refereeing (
                            game_id    NUMBER(19) NOT NULL,
                            referee_id NUMBER(19) NOT NULL,
                            role       VARCHAR2(20 CHAR) NOT NULL,

                            CONSTRAINT pk_refereeing PRIMARY KEY (game_id, referee_id),
                            CONSTRAINT fk_refereeing_game
                                FOREIGN KEY (game_id)
                                    REFERENCES game (id),
                            CONSTRAINT fk_refereeing_referee
                                FOREIGN KEY (referee_id)
                                    REFERENCES referee (id),
                            CONSTRAINT ck_refereeing_role
                                CHECK (role IN ('MAIN', 'ASSISTANT_1', 'ASSISTANT_2', 'FOURTH_REFEREE'))
);

CREATE TABLE report (
                        id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                        game_id     NUMBER(19) NOT NULL,
                        referee_id  NUMBER(19) NOT NULL,
                        user_id     NUMBER(19) NOT NULL,
                        protocol    VARCHAR2(255 CHAR),
                        content     CLOB NOT NULL,
                        report_date TIMESTAMP NOT NULL,
                        status      VARCHAR2(20 CHAR) NOT NULL,
                        analysis_result VARCHAR2(20 CHAR),

                        CONSTRAINT pk_report PRIMARY KEY (id),
                        CONSTRAINT uk_report_protocol UNIQUE (protocol),
                        CONSTRAINT fk_report_game
                            FOREIGN KEY (game_id)
                                REFERENCES game (id),
                        CONSTRAINT fk_report_referee
                            FOREIGN KEY (referee_id)
                                REFERENCES referee (id),
                        CONSTRAINT fk_report_user
                            FOREIGN KEY (user_id)
                                REFERENCES knowball_users (id),
                        CONSTRAINT ck_report_status
                            CHECK (status IN ('NEW', 'UNDER_REVIEW', 'RESOLVED')),
                        CONSTRAINT ck_report_analysis_result
                            CHECK (
                                analysis_result IS NULL
                                    OR analysis_result IN ('POSITIVE', 'NEUTRAL', 'NEGATIVE')
                                )
);

CREATE INDEX idx_game_championship_id
    ON game (championship_id);

CREATE INDEX idx_participation_team_id
    ON participation (team_id);

CREATE INDEX idx_refereeing_referee_id
    ON refereeing (referee_id);

CREATE INDEX idx_report_game_id
    ON report (game_id);

CREATE INDEX idx_report_referee_id
    ON report (referee_id);

CREATE INDEX idx_report_user_id
    ON report (user_id);

CREATE INDEX idx_report_status
    ON report (status);

CREATE INDEX idx_report_date
    ON report (report_date);