CREATE TABLE email_verification_tokens (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) NOT NULL,
    code VARCHAR2(6) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE INDEX idx_email_verification_tokens_email ON email_verification_tokens(email);