BEGIN
EXECUTE IMMEDIATE 'DROP TABLE email_verification_tokens';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
EXECUTE IMMEDIATE 'ALTER TABLE users DROP COLUMN email_verified';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -904 THEN RAISE; END IF;
END;
/