ALTER TABLE REPORT
    ADD (REPORT_DATE_TZ TIMESTAMP(6) WITH TIME ZONE);

UPDATE REPORT
SET REPORT_DATE_TZ =
        FROM_TZ(
                CAST(REPORT_DATE AS TIMESTAMP),
                'America/Sao_Paulo'
        );

ALTER TABLE REPORT
DROP COLUMN REPORT_DATE;

ALTER TABLE REPORT
    RENAME COLUMN REPORT_DATE_TZ TO REPORT_DATE;