CREATE TABLE email_verification_tokens (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255 CHAR) NOT NULL,
    code VARCHAR2(6 CHAR) NOT NULL,
    expires_at  TIMESTAMP NOT NULL,
    used NUMBER(1) DEFAULT 0 NOT NULL,
    verified_at TIMESTAMP
);

CREATE INDEX idx_email_verification_tokens_email ON email_verification_tokens(email);

COMMENT ON TABLE email_verification_tokens IS
    'Códigos de verificação de e-mail enviados durante o cadastro (Etapa 4).';
COMMENT ON COLUMN email_verification_tokens.verified_at IS
    'Momento em que o código foi confirmado com sucesso. Usado para checar se a verificação ainda é recente na hora do registro.';